# .NET workflow with private github packages
name: .NET

env:
    # repository secret PACKAGES_TOKEN is required to access private packages
    NUGET_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_NOLOGO: true
    
on:
  push:
    branches: [ develop, master, feature/* ]
  pull_request:
    branches: [ develop, master ]

defaults:
  run:
    working-directory: src

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
    - name: Restore dependencies
      run:
        dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
